### ISSUE TITLE
Add loading page while report is being generated

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#10]
Create a loading page while the report is being generated instead of staying on the landing page.

Resources to get started:
[Flask loading page](https://stackoverflow.com/questions/48553728/flask-use-javascript-to-display-loading-page-while-waiting-for-task-to-complet/48557581)

**Comment by marshalmiller** [comment]
it appears like the only way to make this work is through some Flask Routes magic. I have tried to do it the same way as JavaScript and HTML but it appears like the only way to carry it over with the data and between pages is through routes. I created a loading.html page that can be used for the template render. We just need to figure out how to trigger the check URL process, call the loading page, and then call the analysis page once it is complete.
