### ISSUE TITLE
Add loading animation when download button is pressed

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#11]
Create a loading animation while files are being generated for download.

**Comment by anmolag10** [comment]
I want to work on this feature.

**Comment by aditirao7** [comment]
@anmolag10 the loading animation should stop after the download is complete, could you do that too?

**Comment by anmolag10** [comment]
I'll fix it.

**Comment by marshalmiller** [comment]
it appears like the only way to make this work is through some Flask Routes magic. I have tried to do it the same way as JavaScript and HTML but it appears like the only way to carry it over with the data and between pages is through routes. I created a loading.html page that can be used for the template render. We just need to figure out how to trigger the check URL process, call the loading page, and then call the analysis page once it is complete.
