### ISSUE TITLE
Add comments to all files

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#12]

**Comment by aditirao7** [comment]
Sure @anishwar-007, it's a flask based application, so you can add comments in the form of docstrings for all the functions in app.py. 
In brief: 
- uploadpdf() requests for a pdf/link, sets session related data and renders the analysis page. 
- pdfdata() extracts pdf info using linkrot
- downloadpdf() is the backend function for downloading reference pdfs.
@marshalmiller are comments necessary for the HTML files?

**Comment by marshalmiller** [comment]
No. I think we are good on that front. Maybe later I'll add some info in the ReadME about of the templates works with the app. But I think we are good without comments. Thank you both!

**Comment by marshalmiller** [comment]
This appears to have been addressed a while ago.
