### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/rottingresearch#21]
I'm trying to setup the continuous integration for the permanent home for the app but I seem to be having issues with the secret. I'm sure it's me not having a full understanding of how it works in Flask. I'm trying to use the GitHub secrets function. I made one called Heroku_Secret and put it in the code but the app still appears to not recognize it has a value. @aditirao7 Any ideas? You've deployed it on your test site. What am I missing?

**Comment by aditirao7** [comment]
@marshalmiller may I know where you are trying to host it since it varies from platform to platform. In heroku you have an option to set environment variables for the app so I just had to assign a value to a variable called APP_SECRET_KEY since that's what python is attempting to derive from the OS (through os.environ.get(...))

**Comment by marshalmiller** [comment]
I was trying to use heroku at the moment. At least test it out. When I tried it though, it gave me that error that the key was not set. Do you have to do it through the terminal on heroku too?

**Comment by aditirao7** [comment]
Oh so on heroku it should work as is, you could use the terminal to set the environment variable like this: `heroku config:set APP_SECRET_KEY=random` or on the heroku app dashboard in the settings tab, subheading: Config Variables.

**Comment by marshalmiller** [comment]
Out of curiosity, or maybe for options, if I were to deploy it on a standard Linux web server, how would I got about doing the secret? I thought the way I just changed the code would have worked for that but it doesn't appear so. Is there some other way to hardcode it that you know of? With GitHub?

**Comment by marshalmiller** [comment]
No worries. I just figured it was worth an ask. I'll make sure that I can get the Heroku up and then I'll close the issue.

**Comment by marshalmiller** [comment]
I Just set the variable in the settings. I called this closed and open another one if I end up deploying outside of heroku.
