### ISSUE TITLE
Create Docker Image

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/rottingresearch#46]
Creating a Docker Image would allow us to test and deploy this app much faster. I'd prefer to use Docker over other containerization solutions, but am open to ideas.

**Comment by M-Faheem-Khan** [comment]
Hi, can you assign this issue to me?

**Comment by M-Faheem-Khan** [comment]
Hey @marshalmiller, I have gone ahead and created a Dockerfile for building the image, Do you think I should also create a `docker-compoose.yml`? If in the future other services/images(db) are used we can create them all together using one file it will also help new developers/consumers quickly setup or test the application.

PR: https://github.com/marshalmiller/rottingresearch/issues/46

Thanks,
M-Faheem-Khan

**Comment by marshalmiller** [comment]
@M-Faheem-Khan A compose file would be amazing!

**Comment by M-Faheem-Khan** [comment]
@marshalmiller I have created the `docker-compose.yml` file and tested it locally it works can I get a PR & merge? :)

**Comment by marshalmiller** [comment]
@M-Faheem-Khan Thank you so much for your work on this. I really appreciate your help. If you don't mind, how did you find our project? I'm so glad you did.

**Comment by M-Faheem-Khan** [comment]
I find the project really interesting mainly because of it utility and the mission. Overtime it will play a vital role researcher/scholars validating this citations which is really important.

**Comment by marshalmiller** [comment]
@M-Faheem-Khan Well thank you for finding value in our mission. I agree. It's a critical issue. I'm working on adding an option to archive all of the links to the InternetArchive as well. That way they will be perfectly preserved. I appreciate your help and encouragement.
