### ISSUE TITLE
Agreement Checkbox

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/rottingresearch#47]
We should add some sort of agreement checkbox. We can add like a tool tip about how the uploader agrees that they have the rights to upload the document or whatever. Just to cover certain liabilities.

**Comment by M-Faheem-Khan** [comment]
Hi, can I take this issue?

**Comment by marshalmiller** [comment]
@M-Faheem-Khan It's all yours. Thank you!

**Comment by M-Faheem-Khan** [comment]
Do we have a privacy policy/terms of service/agreement that I can add to its own page?

**Comment by marshalmiller** [comment]
@M-Faheem-Khan Not yet. Either you can create some filler text or I can create one today.

**Comment by marshalmiller** [comment]
@M-Faheem-Khan I created [https://rottingresearch.org/policies](https://rottingresearch.org/policies). Right now there is only a privacy policy but I will add more. Let me know if there's anything else you need.

**Comment by M-Faheem-Khan** [comment]
@marshalmiller I have added the agreement checkbox whenever you get the change please review. :) 
PR: https://github.com/marshalmiller/rottingresearch/pull/50

**Comment by marshalmiller** [comment]
Address in PR: #50
