### ISSUE TITLE
Redesign Analysis Page

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/rottingresearch#5]
Redesign the Analysis report page.

**Comment by aditirao7** [comment]
Maybe you could add the hacktoberfest label and other relevant labels (bootstrap, react?) so that people with more frontend dev experience can find this issue, I'm sure they'll be more than happy to take it up.

**Comment by marshalmiller** [comment]
@aditirao7 Will do. If there are any places you are feeling lost, feel free to add the issues to this project and I will try to promote them as much as possible to attract others. You took on a very broad task, so we can break it down to tiny tasks for certain things.

**Comment by aditirao7** [comment]
Yep, I'll open a few issues soon. Could you disable the self assignment on issues because people might think the issue is already assigned. I'll also ask a few friends if they're interested in contributing :)

**Comment by marshalmiller** [comment]
@aditirao7 You are my hero. These are great ideas. I'll make sure I change the ReadMe ASAP and add the test site. I'll turn off auto-assign. And seriously, if some of your friends want to help out, I would be so grateful. Thanks.

**Comment by aditirao7** [comment]
Yep @marshalmiller @samspecial, the reason I used only HTML and CSS is because I have limited frontend experience. If using React or Bootstrap can make the code cleaner and more concise then feel free to use it, but either way is fine.
