### ISSUE TITLE
Refactor Code & Adopt Standard Code Linter

### ISSUE THREAD

**Issue by M-Faheem-Khan** [marshalmiller/rottingresearch#53]
The HTML code stinks mainly the `upload.html` because there is no code consistency and the Javascript is all over the place. I believe refactoring it would improve readability and code hygiene. 

**Solution:** Standard Code Lint configuration (Prettier)

Inconsistent Indentation & Closing of Tags  
https://github.com/marshalmiller/rottingresearch/blob/cf3181de677964a656c41debaf366599f2a7c137/templates/upload.html#L86-L126

Javascript Optimzation - JS code can be moved to the bottom(order or priority)
https://github.com/marshalmiller/rottingresearch/blob/cf3181de677964a656c41debaf366599f2a7c137/templates/upload.html#L29-L50

**Comment by mailtodanish** [comment]
I am working on this.

**Comment by marshalmiller** [comment]
This has been addressed in PR #73. Thank you @mailtodanish for yet another great contriubution.
