### ISSUE TITLE
Make analysis page responsive (mobile view)

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#6]
Text continues off-screen in the mobile view, needs to be responsive

Screenshot:
![Screenshot from 2021-10-05 23-18-34 - 1](https://user-images.githubusercontent.com/57457307/136076394-f1b98a76-9e78-442b-aaf4-8403ac264a0d.png)

**Comment by joaovictor3g** [comment]
okay, i'll try reinstall python and pip, thanks for your support! :smile:

**Comment by joaovictor3g** [comment]
Now, I am using the pip version: `pip 21.2.4` and Python 3.9, but i am still receiving an error, as follow:
![Captura de tela de 2021-10-08 19-57-52](https://user-images.githubusercontent.com/55103977/136632876-e8bb6c23-52d1-4ee4-95f2-3a8bbf9d6fa3.png)

**Comment by aditirao7** [comment]
@joaovictor3g from the screenshot I can see that it has collected Flask==1.1.4 while the current version of requirements.txt should collect Flask 2.0.1. Did you pull the latest repository update to your local system? 
As for the environment variable, just run `export APP_SECRET_KEY = "random"` on the terminal before running app.py and it should work.

**Comment by joaovictor3g** [comment]
Ok, i did everything that you said, but runnig app with `python3 app.py` throws the following error: 
![Captura de tela de 2021-10-09 13-41-00](https://user-images.githubusercontent.com/55103977/136667013-34f7b015-6b28-493f-86d1-e0e11b6c939c.png)

**Comment by aditirao7** [comment]
@joaovictor3g what output does `flask --version` give?

**Comment by joaovictor3g** [comment]
Ok, everything worked. I just need to know the easier way to reach analysis page.

**Comment by joaovictor3g** [comment]
As the last error to me finally get solve the issue, i have:  `RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret`. I know it's because of secret key i ran the `export APP_SECRET_KEY=random` but i did not get the expected result.
![Captura de tela de 2021-10-09 15-34-51](https://user-images.githubusercontent.com/55103977/136670312-f6cad818-56c2-4bd7-8338-26cee08837af.png)

**Comment by aditirao7** [comment]
@joaovictor3g the environment variable has to be set everytime, if you opened a new terminal it has to be done there too. To make it easier, you can temporarily change it in the python file:
![Screenshot_20211010-001453~2](https://user-images.githubusercontent.com/57457307/136670634-2b0da9eb-ddd0-47f8-a11b-e257716915dc.png)

To reach the analysis page faster, you can temporarily comment some parts of the python file too: 
![Screenshot_20211010-002227](https://user-images.githubusercontent.com/57457307/136670805-86d6f370-01a7-48fc-8683-909d0393f796.png)

Just make sure you revert these changes before sending in your pull request. Hopefully the page can be made responsive using only the document info part?

**Comment by marshalmiller** [comment]
It does not appear to have worked on my end. Here is a live version for you to test it on. https://rottingresearch.herokuapp.com/

**Comment by joaovictor3g** [comment]
you can see it on screenshot that i sent in the pr message.

**Comment by joaovictor3g** [comment]
Guys, i did not submitted yet the final responsive version because i am very busy with my work, but this weekend most likely i'll make the pull request.

**Comment by marshalmiller** [comment]
Resolved in Pull Request #40. Thank you, @jayeclark.
