### ISSUE TITLE
Fix mobile view

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#61]
The mobile view needs to be made responsive, restructured and redesigned. Respective screenshots are attached below.

![WhatsApp Image 2022-06-27 at 11 35 26 PM (1)](https://user-images.githubusercontent.com/57457307/176008509-796cf0f4-0e2d-47c9-b6f8-d36d5d13090d.jpeg)

![WhatsApp Image 2022-06-27 at 11 35 26 PM](https://user-images.githubusercontent.com/57457307/176008563-5d269b22-4307-4a16-b97e-42e62156fac1.jpeg)

![WhatsApp Image 2022-06-27 at 11 46 50 PM](https://user-images.githubusercontent.com/57457307/176008843-4a0046f9-97d9-4cad-8cd4-01ef4f1eee00.jpeg)

**Comment by Ahnaf-codes** [comment]
would you like the nav to be transparent? and form to be centered? if so assign me

**Comment by marshalmiller** [comment]
@Ahnaf-codes I believe the idea was to have the navigation trimmed so there is not so much white space. As for the form, the issue is that it's not responsive like the results are. Notice the results scale and leave some margin on the side. You have to move around in order to see the whole form on the home page. What do you think? Would you still be interested in picking up this issue?

**Comment by Ahnaf-codes** [comment]
Yeah i think i can do it! Assign me

**Comment by Ahnaf-codes** [comment]
![Screenshot 2022-09-30 at 14-33-29 Rotting Research](https://user-images.githubusercontent.com/102795582/193228277-5d5b1cd7-8b56-4c83-8351-4c7b9e760239.png)
is this a good size for the nav?

**Comment by Ahnaf-codes** [comment]
is this good?
![Screenshot 2022-09-30 at 14-44-32 Rotting Research](https://user-images.githubusercontent.com/102795582/193230676-2e66ba37-3f82-420e-b33d-36b611e0ab71.png)

**Comment by marshalmiller** [comment]
@Ahnaf-codes This looks great for the form.

**Comment by Ahnaf-codes** [comment]
Hey @marshalmiller I've sent the pr

**Comment by marshalmiller** [comment]
@Ahnaf-codes Thank you. I will wait until tomorrow to merge, so you get credit, but it looks good. Thank you so much for helping out with our project. I appreciate it.
