### ISSUE TITLE
Unecessary scroll on landing page (desktop view)

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#62]
The landing page is overflowing and causing unnecessary horizontal and vertical scroll on desktop view. Screenshot attached below.

![Screenshot from 2022-06-27 23-23-22](https://user-images.githubusercontent.com/57457307/176006408-a3e46c71-061f-4f9c-98d6-05a456c52d05.png)

**Comment by marshalmiller** [comment]
Addressed in PR #63

**Comment by aditirao7** [comment]
It appears this same extra scroll is present on the analysis page as well. Will attempt to fix it using this as reference
