### ISSUE TITLE
Fix code scanning alert - Incomplete URL substring sanitization

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/rottingresearch#66]
Tracking issue for:
- [ ] https://github.com/marshalmiller/rottingresearch/security/code-scanning/5

**Comment by mailtodanish** [comment]
@marshalmiller  I am not able to access https://github.com/marshalmiller/rottingresearch/security/code-scanning/5

**Comment by marshalmiller** [comment]
@mailtodanish You addressed both issues in your one PR #70. They were separate for DOIs and ArXivs. I am testing the build now, but so far so good. I will close both once I can verify everything is stable. Thank you so much for your help. I appreciate it.

**Comment by marshalmiller** [comment]
@mailtodanish This was successfully addressed in PR #70. I assigned it to you so that people know you were the fix, but I'm not sure it will count separately for Hacktoberfest. Sorry.
