### ISSUE TITLE
Fix code scanning alert - Incomplete URL substring sanitization

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/rottingresearch#67]
Tracking issue for:
- [ ] https://github.com/marshalmiller/rottingresearch/security/code-scanning/4

**Comment by mailtodanish** [comment]
Could you please explain me this issue with example.

**Comment by marshalmiller** [comment]
@mailtodanish If you click the link above, it can explain some of the issues. But essentially, the current way the program works, it would allow others to spoof a URL simply by putting "doi.org" or "arxiv.org" in the URL somewhere.

**Comment by mailtodanish** [comment]
@marshalmiller  below link is not working for me 404 error. 
`https://github.com/marshalmiller/rottingresearch/security/code-scanning/4`

**Comment by marshalmiller** [comment]
@mailtodanish Oh. Sorry. That must be some sort of permissions thing. Since I am the maintainer, I guess contributors can't see that section. I have attached a PDF of the page. If this isn't of much help, this might be something I have to address myself. Thank you for bringing this up. I had no idea of this limitation. I appreciate all of your help with this.

[Incomplete URL substring sanitization · Code scanning alert #4 · marshalmiller_rottingresearch.pdf](https://github.com/marshalmiller/rottingresearch/files/9667119/Incomplete.URL.substring.sanitization.Code.scanning.alert.4.marshalmiller_rottingresearch.pdf)

**Comment by mailtodanish** [comment]
I will work on this.

**Comment by marshalmiller** [comment]
@mailtodanish You did an amazing job on this. Thank you so much for your help. It was fully resolved in PR #70.
