### ISSUE TITLE
Make better-looking javascript alerts

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/rottingresearch#8]
Alerts are generated when the user submits without uploading a file/url or when the file/url is not a pdf. 

![Screenshot from 2021-10-05 23-35-51](https://user-images.githubusercontent.com/57457307/136078571-c79417ea-7dcd-4416-9137-43e8ae5e77b5.png)

The alerts are generated using the standard window.alert() and don't look that great. Improve alert design.

**Comment by marshalmiller** [comment]
Thank you. It's all yours.

**Comment by M-Faheem-Khan** [comment]
@marshalmiller I see there has been no progress on this ticket if @angelinjohn is not working on this can I take it?

**Comment by marshalmiller** [comment]
@M-Faheem-Khan I've added you to the assignees. Feel free to go for it. Thank you for your help.

**Comment by M-Faheem-Khan** [comment]
@marshalmiller I have added the new alerts please have a review. :) 
PR: #51

**Comment by marshalmiller** [comment]
Addressed in PR: #51
